[package]
name = "stefans-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
schemars = { version = "1", optional = true }
serde = { version = "1", features = ["derive"], optional = true }
thiserror = "2"

[features]
default = ["serde", "schemars", "std"]
serde = ["dep:serde"]
schemars = ["dep:schemars"]
std = []
